### PR TITLE
Support for setting multiple icons in one label or button

### PR DESCRIPTION
**Pull request by 3pehrbehroozi**
- added support for setting icons array for UILabel and UIButton
- cleaned up redundant codes
- added a function for generating attributed string to be used in UILabel and UIButtons

### CODE REVIEW

**Comment by 3pehrbehroozi** [comment]
Any plans for review or merge? @ranesr 
If you have a plan for reviewing my pr then tell me to resolve conflicts

Thanks

**Comment by ranesr** [comment]
@3pehrbehroozi Yes, will be happy to review it once you have resolved conflicts.

**Comment by 3pehrbehroozi** [comment]
Hi,
The conflicts has been resolved.
I will be happy to hear from you @ranesr.
Thanks

**Comment by ranesr** [comment]
Thanks @3pehrbehroozi. I have merged the code and it will be added in the next release.

**Pull request merged**
